version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marvelSnapDeck
    ports:
      - "3306:3306"
    volumes:
      - ./../Database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      UPLOAD_LIMIT: 100M
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/marvelSnapDeck
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8082:80"
    depends_on:
      - db

  marvel-snap-deck:
    image: momcilovicluka/marvel-snap-deck
    container_name: marvel-snap-deck
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/marvelSnapDeck?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver